### ISSUE TITLE
Crash on attempt to load a file

### ISSUE THREAD

**Issue by Komander-3** [DanielElam/bf2-sound-import#2]
Hello! Right from the start, I'll mention that I attempted to use it on Mirror's Edge Catalyst

I've attempted to rebuild the tool with MirrorsEdgeSDK.dll

But the result is the same as when running the tool without that "fix"

I get this crash error in Frosty Editor:

Couldn't find field taskCancelButton in type FrostyEditor.MainWindow
Parameter name: fieldName

   at DanDev.FrostySoundImport.ReflectionHelper.GetFieldValue[T](Object obj, String fieldName) in C:\Users\michu\Downloads\bf2-sound-import-master\FrostySoundImport\ReflectionHelper.cs:line 30
   at DanDev.FrostySoundImport.DanDev.FrostySoundImport.FrostyTask2.Begin(String task, String initialStatus, Action`1 cancelAction) in C:\Users\michu\Downloads\bf2-sound-import-master\FrostySoundImport\FrostyTask2.cs:line 24
   at DanDev.FrostySoundImport.Program.<OnImportSoundCommand>d__10.MoveNext() in C:\Users\michu\Downloads\bf2-sound-import-master\FrostySoundImport\Program.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)|
 

 This goes beyond my level of knowledge of C#, but I thought it might be relevant to fix this issue, as I've seen this tool being used for multiple games!
 
 It happens regardless of opening a .wav or .mp3 file, also regardless of their properties

**Comment by DanielElam** [comment]
Hi, sorry I've reset my PC recently and don't have any frostbite games installed so I can't be of much help. It looks like it's caused by an update to Frosty Editor. You could try it with an older version, or comment out the call to "FrostyTask2.Begin" in OnImportSoundCommand in Program.cs

Interestingly there's a try/catch inside that method so you shouldn't be getting a crash regardless. If you're running it through Visual Studio then you might get away with just pressing Continue when the error pops up.

**Comment by Komander-3** [comment]
It does work now!

But it does not work on .wav files with multiple layers, is it possible to even accomplish multilayer import with how ealayer3 converter currently functions?

**Comment by Komander-3** [comment]
oh and thanks for your effort with the tool :)

**Comment by DanielElam** [comment]
> But it does not work on .wav files with multiple layers, is it possible to even accomplish multilayer import with how ealayer3 converter currently functions?

It's been a while but I don't remember anything about layers. If you mean channels then I think it should use the same number of channels that the game asset used, but I never tested anything besides mono/stereo.

**Comment by Komander-3** [comment]
it apparently doesn't work for more than 2 channels... thanks for the help anyway :)

**Comment by Komander-3** [comment]
To sum things up: the tool currently doesn't support more than 2 layered tracks, but with a little tweak, it gets it's job done
