### ISSUE TITLE
Unable to open SoundImport

### ISSUE THREAD

**Issue by ju1cyjames** [DanielElam/bf2-sound-import#3]
Error opening executable even after prerequisite and proper folder directory is achieved

`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at FrostyEditor.App..ctor()
   at DanDev.FrostySoundImport.Program.<>c.<Main>b__6_0()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at DanDev.FrostySoundImport.Program.Main(String[] args)
`

**Comment by ju1cyjames** [comment]
I have the redistributional installed and the exes in the same folder as the editor and it still doesn't work. Does it not work with later versions of frosty editor?

**Comment by GhostZypleX** [comment]
I found a solution how to start the program, you need to download version 1.0.5.9 of Frosty editor, you can find it if you search on  google for Frosty editor 1.0.5.9
